spring:
  application:
    name: document-editing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/document_editing
    username: postgres
    password: mentee
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8083

version-control-service:
  url: http://localhost:8084
